paths:
  /api/products:
    get:
      tags:
        - Products
      summary: Obtiene todos los productos
      responses:
        '200':
          description: Operaccion exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
      security:
        - bearerAuth: ["USER", "ADMIN", "PREMIUM"]
    post:
      tags:
        - Products
      summary: Crear un nuevo producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Operaccion exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'

  /api/products/{pid}:
    get:
      tags:
        - Products
      summary: Obtener producto por id
      parameters:
        - name: pid
          in: path
          required: true
          description: Id del producto
          schema:
            type: string
      responses:
        '200':
          description: Operaccion exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
      security:
        - bearerAuth: ["USER", "ADMIN", "PREMIUM"]
    put:
      tags:
        - Products
      summary: Actualizar producto por Id
      parameters:
        - name: pid
          in: path
          required: true
          description: Id del producto
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Operaccion exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
      security:
        - bearerAuth: ["ADMIN", "PREMIUM"]
    delete:
      tags:
        - Products
      summary: Eliminar productor por id
      parameters:
        - name: pid
          in: path
          required: true
          description: Id del producto
          schema:
            type: string
      responses:
        '200':
          description: Operaccion exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
      security:
        - bearerAuth: ["ADMIN", "PREMIUM"]

components:
  schemas:
    Product:
      type: object
      properties:
        title:
          type: string
          description: The title of the product.
        description:
          type: string
          description: Description of the product.
        price:
          type: number
          description: Price of the product.
        thumbnails:
          type: array
          items:
            type: string
          description: List of product thumbnails.
        code:
          type: string
          description: Unique product code.
        category:
          type: string
          description: Product category.
        stock:
          type: integer
          description: Quantity in stock of the product.
        status:
          type: boolean
          description: Product status (active/inactive).
        owner:
          type: string
          description: ID of the product owner.
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT